# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build splitkb_aurora_sweep nice_nano_v2'
# swweeep
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_sweep_left","splitkb_aurora_sweep_right"]'
      alphas: '["qwerty"]'
      nav: '["default"]'
      clipboard: '["default","fun","mac","win"]'
      layers: '["default"]'


